services:
  - type: web
    name: smart-resume-screener-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_MODEL_NAME
        value: gemini-2.5-flash
      - key: SENTENCE_MODEL_NAME
        value: all-mpnet-base-v2
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
    maxDuration: 900
